#!/usr/bin/env ruby

# Trap ^C
Signal.trap("INT") {
  puts "\nCtrl-C detected. Exiting..."
  sleep 0.1
  exit
}

$:.unshift(File.expand_path("../../lib", __FILE__))
require "s3-antivirus"
require "s3_antivirus/cli"

S3Antivirus::CLI.start(ARGV)
